default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: welcome_to_the_petshop_development

test:
  <<: *default
  database: welcome_to_the_petshop_test

production:
  <<: *default
  database: welcome_to_the_petshop_production
